FROM gettyimages/spark
ADD ./SparkFinnCars-1.0-SNAPSHOT.jar /usr/src/sparkfinncars/
#WORKDIR /usr/src/sparkfinncars
#ENTRYPOINT ["spark-submit","--class", "ttorbjornsen.finncars.Batch", "/usr/src/sparkfinncars/SparkFinnCars-1.0-SNAPSHOT.jar"]
#ENTRYPOINT ["spark-submit","--class", "ttorbjornsen.finncars.StreamFromKafka", "/usr/src/sparkfinncars/SparkFinnCars-1.0-SNAPSHOT.jar"]
